name: tasket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0

  # state management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # UI
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.1.0
  material_symbols_icons: ^4.2719.2
  firebase_vertexai: ^1.6.0
  # flutter_slidable: ^4.0.0
  # smooth_page_indicator: ^1.2.1

  # utils
  intl: ^0.18.1
  # flutter_screenutil: ^5.9.0
  # shared_preferences: ^2.0.15
  # uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
