// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCrzv0SIpENF2W1czaUDz5jCRAvyCjfY',
    appId: '1:375153892072:web:afd9e52b1242036dc1875d',
    messagingSenderId: '375153892072',
    projectId: 'fir-flutter-codelab-d2972',
    authDomain: 'fir-flutter-codelab-d2972.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d2972.firebasestorage.app',
    measurementId: 'G-RLPTYGKXF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZqrAX0aKQTPOoiDlNMQZsQ16yRhohvQ',
    appId: '1:375153892072:android:5c264d5d38f24227c1875d',
    messagingSenderId: '375153892072',
    projectId: 'fir-flutter-codelab-d2972',
    storageBucket: 'fir-flutter-codelab-d2972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmOSbEFFahZJEm4CaZ-1cfAapfMRAb_Cg',
    appId: '1:375153892072:ios:edce5956a8d264c6c1875d',
    messagingSenderId: '375153892072',
    projectId: 'fir-flutter-codelab-d2972',
    storageBucket: 'fir-flutter-codelab-d2972.firebasestorage.app',
    iosBundleId: 'com.example.tasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmOSbEFFahZJEm4CaZ-1cfAapfMRAb_Cg',
    appId: '1:375153892072:ios:edce5956a8d264c6c1875d',
    messagingSenderId: '375153892072',
    projectId: 'fir-flutter-codelab-d2972',
    storageBucket: 'fir-flutter-codelab-d2972.firebasestorage.app',
    iosBundleId: 'com.example.tasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCrzv0SIpENF2W1czaUDz5jCRAvyCjfY',
    appId: '1:375153892072:web:524e0cbdd846a859c1875d',
    messagingSenderId: '375153892072',
    projectId: 'fir-flutter-codelab-d2972',
    authDomain: 'fir-flutter-codelab-d2972.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d2972.firebasestorage.app',
    measurementId: 'G-JK683Q49WM',
  );
}
